# -*- coding: utf-8 -*-
"""Analise_Vacinas_Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J0ti0-iGbwxZJV7iSRrAzophP8H8snSb

# Análise Exploratória da Vacinação no Distrito Federal
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/Covid_DF.csv', sep=';')
df.head()

df.info()

df.count()

"""# Problema 

- Qual a idade mais vacinada? 

- Qual o sexo mais vacinado?

- Quantas doses (1°,2° e única) foram aplicadas?

- Qual a idade dos sexos vacinados?

## Qual a idade mais vacinada? 

- 39 anos
"""

df.describe()

df['paciente_idade'].mode()

df[['paciente_idade']].value_counts()

(47758/2097229)*100

"""A média da idade das pessoas vacinadas é 50 anos, a variabilidade média entre essas idades é de 16.41 anos, sendo assim no intervalo entre a idade mínima, 3 anos, e a idade máxima, 121 anos, o desvio padrão foi 16.41 anos. 

A idade mais frequente dos vacinados é 39 anos. Os vacinados com 39 anos equivale a 2.27% de todos os vacinados no DF. 

Existem 4 pessoas que não declararam suas idades. 

25% das pessoas vacinadas têm até 38 anos. Metade (50%) dos vacinados têm até 49 anos. 75% dos vacinados têm até 63 anos e 25% dos vacinados têm mais de 63 anos. 
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np  
import matplotlib.pyplot as plt 
# % matplotlib inline

df.boxplot(column= ['paciente_idade'],grid=True,color='green')

"""Alguns valores merecem ser analisados como a idade acima dos 100 anos e menor de 9 anos de idade, pois pode ser um erro de preenchimento"""

plt.figure(figsize=(7,7))
plt.title('Idade - Vacina Covid')
plt.xlabel('Idade')
plt.ylabel('Frequência Absoluta')
plt.hist(df['paciente_idade'], 20, color='green', alpha=0.7,edgecolor='white')
plt.show()

"""## Qual o sexo mais vacinado?"""

df['paciente_enumsexobiologico'].mode()

df['paciente_enumsexobiologico'].value_counts()

1186695/(1186695+910530+4)

1565434/(1565434+1447284)

"""1.186.695 mulheres foram vacinadas no DF, enquanto 910.530 homens foram vacinados. Portanto, 56.58% da população vacinada, até o dia 16/08, são mulheres

"""

plt.figure(figsize=(7,7))
df['paciente_enumsexobiologico'].value_counts().plot(kind='bar', rot=0)
plt.xlabel("Sexo", labelpad=14)
plt.ylabel("Quantidade de Pessoas (em milhões)", labelpad=14)
plt.title("Sexo dos Vacinados de COVID no DF", y=1.02);

"""## Quantas doses (1°,2° e única) foram aplicadas?"""

df['vacina_descricao_dose'].value_counts()

567691 +38690

"""Foram aplicadas 1.490.848 primeira dose, 567.691 segunda dose e 38.690 doses únicas. Portanto, até o dia 16/08, 606.381 pessoas no DF estão vacinadas de forma efetiva"""

df['vacina_descricao_dose'].value_counts().plot(kind='bar',figsize=(7, 7), rot=0)
plt.xlabel("Doses", labelpad=14)
plt.ylabel("Quantidade de Doses (em milhões)", labelpad=14)
plt.title("Doses de Vacina de COVID no DF", y=1.02);

df.groupby('vacina_descricao_dose')['vacina_nome'].value_counts()

df2 = df.groupby(by=['vacina_descricao_dose'])['vacina_nome'].value_counts().reset_index(name='Quantidade')
df2

import re

def Clean_names(City_name):
    if re.search('Covishield', City_name):
        return 'Covishield'
    elif re.search('Pfizer', City_name):
        return 'Pfizer'
    elif re.search('Sinovac', City_name):
        return 'Sinovac'
    elif re.search('AstraZeneca', City_name):
        return 'AstraZeneca'
    elif re.search('Janssen', City_name):
        return 'Janssen'
    else:
        return City_name

# Updated the city columns
df2['Legenda'] = df2['vacina_nome'].apply(Clean_names)

"""Em relação a primeira dose, a vacina mais aplicada foi a Covishield com 619.980 aplicações, seguindo a Pfizer com 434.585 aplicações, a Sinovac com 374.732 aplicações e a AstraZeneca com 61.551 aplicações. Cerca de 41% dos vacinados na primeira dose foram vacinados com a Covishield.

Em relação a segunda dose, a vacina mais aplicada foi a Sinovac com 309.343 aplicações, seguindo a Covishield com 228.526 aplicações, a AstraZeneca com 20.650 aplicações e a Pfizer com 9.172 aplicações. Cerca de 54% dos vacinados na segunda dose foram vacinados com a Sinovac.
"""

df2

import seaborn as sns

# plot barplot
plt.figure(figsize=(7,7))
sns.set(font_scale=1.2)

sns.barplot(x="vacina_descricao_dose",
           y="Quantidade",
           hue="Legenda",
           data=df2)

"""## Qual a idade dos sexos vacinados"""

df3 = df.groupby(by=['paciente_idade'])['paciente_enumsexobiologico'].value_counts().reset_index(name='count')

df3.head()

df3 = df3.pivot(index='paciente_idade', columns='paciente_enumsexobiologico', values='count').add_prefix('P').reset_index()

df3.head()

df3 = df3.fillna(0)

df3['soma'] = df3.PF + df3.PM
df3['PF_P'] = (df3.PF/df3.soma)*100
df3['PM_P'] = (df3.PM/df3.soma)*100
df3

fields = ['PF_P','PM_P']
colors = ['#DB7093', '#6959CD']
labels = ['F','M']

fig, ax = plt.subplots(1, figsize=(16, 8))
plt.bar(df3.paciente_idade, df3['PF_P'], color = '#DB7093', width =1)
plt.bar(df3.paciente_idade, df3['PM_P'], bottom = df3['PF_P'], color = '#6959CD', width =1)

# x and y limits
plt.xlim(0, 125)
plt.ylim(0, 105)

# remove spines
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.spines['top'].set_visible(False)
ax.spines['bottom'].set_visible(False)

#grid
ax.set_axisbelow(True)
ax.yaxis.grid(color='gray', linestyle='dashed', alpha=0.7)


plt.legend(labels, ncol = 4, bbox_to_anchor=([1, 1.05, 0, 0]), frameon = False)
plt.ylabel("Porcentagem", labelpad=14)
plt.xlabel("Idade dos Pacientes", labelpad=14)

plt.title('Porcentagem Sexo por Idade dos Vacinados no DF', loc='left')
plt.show()

